config/routes.rb
Rails.application.routes.draw do
  get "develop_cocktails/new"
  get "develop_cocktails/create"
  get "develop_cocktails/index"
  get "develop_cocktails/show"
  get "games/index"
  get "games/show"
  get "games/submit"
  get "cocktails/index"
  get "cocktails/new"
  get "cocktails/create"
  get "cocktails/show"
  get "ingredients/new"
  get "ingredients/create"
  #get "user/new"
  #get "user/create"
  #get "dashboard/index"
  #get "sessions/new"
  #get "sessions/create"
  #get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "sessions#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "dashboard#index"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/users", to: "users#index"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients", to: "ingredients#index"
  get "/cocktail_game", to: "games#index", as: "cocktail_game"
  get "/cocktail_game/:id", to: "games#show", as: "play_cocktail_game"
  post "/cocktail_game/:id/submit", to: "games#submit", as: "submit_cocktail_guess"
  resources :cocktails, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :develop_cocktails
end

app/models/develop_cocktail.rb
class DevelopCocktail < ApplicationRecord
    has_many :develop_cocktail_ingredients, dependent: :destroy
    has_many :ingredients, through: :develop_cocktail_ingredients
    accepts_nested_attributes_for :develop_cocktail_ingredients, allow_destroy: true
end

app/controllers/develop_cocktails_controller.rb
class DevelopCocktailsController < ApplicationController
  def new
    @develop_cocktail = DevelopCocktail.new
    2.times {@develop_cocktail.develop_cocktail_ingredients.build} #minimum amount of ingredients for a cocktail
    @ingredients = Ingredient.all
  end

  def create
    @develop_cocktail = DevelopCocktail.new(develop_cocktail_params)
    if @develop_cocktail.save
      redirect_to develop_cocktails_path, notice: "Cocktail in development."
    else
      @ingredients = Ingredient.all
      render :new
    end
  end

  def index
    @develop_cocktails = DevelopCocktail.includes(:ingredients)
    if params[:search].present?
      @develop_cocktails = @develop_cocktails.where("name ILIKE ?", "%#{params[:search]}%")
    end
    if params[:ingredient].present?
      @develop_cocktails = @develop_cocktails.joins(:ingredients).where("ingredients.name ILIKE ?", "%#{params[:ingredient]}%").distinct
    end
  end

  def edit
    @develop_cocktail = DevelopCocktail.find(params[:id])
    @ingredients = Ingredient.all
  end

  def update
    @develop_cocktail = DevelopCocktail.find(params[:id])
    if @develop_cocktail.update(develop_cocktail_params)
      redirect_to develop_cocktails_path, notice: "Cocktail updated."
    else
      @ingredients = Ingredient.all
      render :edit
    end
  end

  def destroy
    @develop_cocktail = DevelopCocktail.find(params[:id])
    @develop_cocktail.destroy
    redirect_to develop_cocktails_path, notice: "Cocktail destroyed."
  end

  def show
    @develop_cocktail = DevelopCocktail.find(params[:id])
  end

  private
  def develop_cocktail_params
    params.require(:develop_cocktail).permit(:name, :glass, :method, :garnish, develop_cocktail_ingredients_attributes: [:id, :ingredient_id, :quantity, :_destroy])
  end
end

app/helpers/develop_cocktails_helper.rb
module DevelopCocktailsHelper
end

app/views/develop_cocktails/create.html.erb
<h1>DevelopCocktails#create</h1>
<p>Find me in app/views/develop_cocktails/create.html.erb</p>

app/views/develop_cocktails/edit.html.erb
<h1>Cocktail development - edit</h1>
<div class="container mt-5">
<% unless pin_login? %>
<%= form_with model: @develop_cocktail, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :glass, "Glass" %>
      <%= f.text_field :glass, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :method %>
      <%= f.select :method, ["Build", "Stir", "Shake", "Throw", "Muddle"], {}, class: "form-select" %>
    </div>

    <div class="mb-3">
      <%= f.label :ice, "Ice" %>
      <%= f.text_field :ice, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :garnish, "Garnish" %>
      <%= f.text_field :garnish, class: "form-control" %>
    </div>

    <h4>Ingredients</h4> <!--selection of ingredients from list -->
    <div id="ingredients">
      <%= f.fields_for :develop_cocktail_ingredients do |ci| %>
        <div class="row mb-2 ingredient-fields">
          <div class="col-md-5">
            <%= ci.label :ingredient_id, "Ingredient" %>
            <%= ci.collection_select :ingredient_id, @ingredients, :id, :name, {include_blank: true}, class: "form-select" %>
          </div>
          <div class="col-md-3">
            <%= ci.label :quantity, "Quantity in ml" %>
            <%= ci.number_field :quantity, class: "form-control", min: 0, step: 0.01 %>
          </div>
          <div class="col-md-2">
      <div class="form-check mt-4">
        <%= ci.check_box :_destroy, class: "form-check-input" %>
        <%= ci.label :_destroy, "Remove", class: "form-check-label" %>
      </div>
    </div>
        </div>
      <% end %>
    </div>

    <button type="button" id="add-ingredient" class="btn btn-outline-secondary mt-2">Add ingredient</button>

    <div class="mt-4">
      <%= f.submit "Update cocktail", class: "btn btn-success" %>
    </div>
  <% end %>
</div>
<% end %>

<script> <!--adding one more ingredient -->
  document.addEventListener("DOMContentLoaded", () => {
    const addButton = document.getElementById("add-ingredient");
    const container = document.getElementById("ingredients");
    const form = document.getElementById("cocktail-form");
    let index = <%= @develop_cocktail.develop_cocktail_ingredients.size %>;
    const ingredientOptions = `<option value=""></option><%= options_from_collection_for_select(@ingredients, :id, :name) %>`;
    addButton.addEventListener("click", (e) => {
      e.preventDefault();
      const newIngredient = document.createElement("div");
      newIngredient.classList.add("row", "mb-2", "ingredient-fields");
      newIngredient.innerHTML = `
        <div class="col-md-5">
          <label>Ingredient</label>
          <select name="cocktail[cocktail_ingredients_attributes][${index}][ingredient_id]" class="form-select">
            ${ingredientOptions}
          </select>
        </div>
        <div class="col-md-3">
          <label>Quantity (ml)</label>
          <input type="number" name="cocktail[cocktail_ingredients_attributes][${index}][quantity]" class="form-control" min="1">
        </div>
      `;
      container.appendChild(newIngredient);
      index++;
    });

    form.addEventListener("submit", (e) => {
      const ingredientField = container.querySelectorAll(".ingredient-fields");
      let isValid = true;

      ingredientField.forEach(row => {
        const select = row.querySelector("select");
        const quantity = row.querySelector("input[type='number']");

        if (!select.value || !quantity.value || parseInt(quantity.value) <= 0) {
          isValid = false;
        }
      });
      if (!isValid) {
        e.preventDefault();
        alert("Insert a valid input.");
      }
    });
  });
</script>

app/views/develop_cocktails/index.html.erb
<h1>Cocktail development</h1>
<div class="container mt-5">
<% unless pin_login? %>
  <% if @develop_cocktails.any? %>
    <% @develop_cocktails.each do |develop_cocktail| %>
      <div class="card mb-3">
        <div class="card-body">
          <h4><%= develop_cocktail.name %></h4>
          <p>Method: <%= develop_cocktail.method %></p>
          <p>Glass: <%= develop_cocktail.glass %></p>
          <p>Ice: <%= develop_cocktail.ice.presence || "none" %></p>
          <p>Garnish: <%= develop_cocktail.garnish.presence || "none" %></p>
          <p>Ingredients:</p>
          <ul>
            <% develop_cocktail.develop_cocktail_ingredients.each do |ci| %>
              <li><%= ci.ingredient.name %> <%= ci.quantity %> ml</li>
            <% end %>
          </ul>
          <% if current_user.role.to_s.downcase == "manager" || current_user.role.to_s.downcase == "supervisor" %>
            <%= link_to "Edit", edit_develop_cocktail_path(develop_cocktail), class: "btn btn-sm btn-outline-secondary me-2" %>
            <%= button_to "Delete", develop_cocktail_path(develop_cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% else %>
      <p>No developed cocktails yet.</p>
    <% end %>
  <% if current_user.role.downcase == "manager" || current_user.role.downcase == "supervisor" %>
    <%= link_to "Develop cocktail", new_develop_cocktail_path, class: "btn btn-outline-secondary mt-3" %>
  <% end %>
<% end %>
</div>

app/views/develop_cocktails/new.html.erb
<h1>Develop a new cocktail</h1>

<div class="container mt-5">
<% unless pin_login? %>
<%= form_with model: @develop_cocktail, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :glass, "Glass" %>
      <%= f.text_field :glass, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :method %>
      <%= f.select :method, ["Build", "Stir", "Shake", "Throw", "Muddle"], {}, class: "form-select" %>
    </div>

    <div class="mb-3">
      <%= f.label :ice, "Ice" %>
      <%= f.text_field :ice, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :garnish, "Garnish" %>
      <%= f.text_field :garnish, class: "form-control" %>
    </div>

    <h4>Ingredients</h4> <!--selection of ingredients from list -->
    <div id="ingredients">
      <%= f.fields_for :develop_cocktail_ingredients do |ci| %>
        <div class="row mb-2 ingredient-fields">
          <div class="col-md-5">
            <%= ci.label :ingredient_id, "Ingredient" %>
            <%= ci.collection_select :ingredient_id, @ingredients, :id, :name, {include_blank: true}, class: "form-select" %>
          </div>
          <div class="col-md-3">
            <%= ci.label :quantity, "Quantity in ml" %>
            <%= ci.number_field :quantity, class: "form-control", min: 0, step: 0.01 %>
          </div>
        </div>
      <% end %>
    </div>

    <button type="button" id="add-ingredient" class="btn btn-outline-secondary mt-2">Add ingredient</button>

    <div class="mt-4">
      <%= f.submit "Develop cocktail", class: "btn btn-success" %>
    </div>
  <% end %>
  <% end %>
</div>

<script> <!--adding one more ingredient -->
  document.addEventListener("DOMContentLoaded", () => {
    const addButton = document.getElementById("add-ingredient");
    const container = document.getElementById("ingredients");
    const form = document.getElementById("cocktail-form");
    let index = <%= @develop_cocktail.develop_cocktail_ingredients.size %>;
    const ingredientOptions = `<option value=""></option><%= options_from_collection_for_select(@ingredients, :id, :name) %>`;

    addButton.addEventListener("click", (e) => {
      e.preventDefault();
      const newIngredient = document.createElement("div");
      newIngredient.classList.add("row", "mb-2", "ingredient-fields");
      newIngredient.innerHTML = `
        <div class="col-md-5">
          <label>Ingredient</label>
          <select name="cocktail[cocktail_ingredients_attributes][${index}][ingredient_id]" class="form-select">
            ${ingredientOptions}
          </select>
        </div>
        <div class="col-md-3">
          <label>Quantity (ml)</label>
          <input type="number" name="cocktail[cocktail_ingredients_attributes][${index}][quantity]" class="form-control" min="1">
        </div>
      `;
      container.appendChild(newIngredient);
      index++;
    });

    form.addEventListener("submit", (e) => {
      const ingredientField = container.querySelectorAll(".ingredient-fields");
      let isValid = true;
      ingredientField.forEach(row => {
        const select = row.querySelector("select");
        const quantity = row.querySelector("input[type='number']");

        if (!select.value || !quantity.value || parseInt(quantity.value) <= 0) {
          isValid = false;
        }
      });
      if (!isValid) {
        e.preventDefault();
        alert("Insert a valid input.");
      }
    });
  });
</script>

app/views/develop_cocktails/show.html.erb
<h1>DevelopCocktails#show</h1>
<p>Find me in app/views/develop_cocktails/show.html.erb</p>