config/routes.rb
Rails.application.routes.draw do
  get "develop_cocktails/new"
  get "develop_cocktails/create"
  get "develop_cocktails/index"
  get "develop_cocktails/show"
  get "games/index"
  get "games/show"
  get "games/submit"
  get "cocktails/index"
  get "cocktails/new"
  get "cocktails/create"
  get "cocktails/show"
  get "ingredients/new"
  get "ingredients/create"
  #get "user/new"
  #get "user/create"
  #get "dashboard/index"
  #get "sessions/new"
  #get "sessions/create"
  #get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "sessions#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "dashboard#index"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/users", to: "users#index"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients", to: "ingredients#index"
  get "/cocktail_game", to: "games#index", as: "cocktail_game"
  get "/cocktail_game/:id", to: "games#show", as: "play_cocktail_game"
  post "/cocktail_game/:id/submit", to: "games#submit", as: "submit_cocktail_guess"
  resources :cocktails, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :develop_cocktails
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :cocktail_ingredients
    has_many :cocktail, through: :cocktail_ingredients
    validates :name, presence: true
    validates :category, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_manager, only: [:new, :create, :edit, :update, :destroy]

  def index
    @categories = Ingredient.distinct.pluck(:category) #get desired attribute
    @ingredients = Ingredient.all
  
    if params[:search].present?
      @ingredients = @ingredients.where("name ILIKE ?", "%#{params[:search]}%")
    end
  
    if params[:category].present?
      @ingredients = @ingredients.where(category: params[:category])
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to dashboard_path, notice: "Ingredient added."
    else
      render :new, alert: "Ingredient not added."
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path, notice: "Ingredient updated."
    else
      render :edit
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.cocktail_ingredients.exists?
      redirect_to ingredients_path, alert: "Ingredient used in cocktails."
    else
      @ingredient.destroy
      redirect_to ingredients_path, notice: "Ingredient deleted."
    end
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :category, :description, :alcohol_percentage)
  end

  def require_manager
    unless current_user.role.downcase == "manager"
      redirect_to dashboard_path, alert: "Access denied."
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<div class="container mt-5">

  <% unless pin_login? %>
    <%= form_with model: @ingredient, local: true do |form| %>
      <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :category %>
        <%= form.text_field :category, list: "category-options", class: "form-control", placeholder: "Category" %>
        <datalist id="category-options">
          <% Ingredient.distinct.pluck(:category).compact.each do |cat| %>
            <option value="<%= cat %>">
          <% end %>
        </datalist>
      </div>

      <div class="mb-3">
        <%= form.label :description %>
         <%= form.text_field :description, class: "form-control", rows: 3 %>
      </div>

      <div class="mb-3">
        <%= form.label :alcohol_percentage %>
        <%= form.number_field :alcohol_percentage, class: "form-control" %>
      </div>

      <%= form.submit "Update ingredient", class: "btn btn-success mt-3" %>
    <% end %>
  <% end %>
</div>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<div class="container mt-5">
  <%= form_with url: ingredients_path, method: :get, local: true, class: "row g-3 mb-4" do |form| %>
    <div class="col-md-6">
      <%= form.label :search, "Search by name" %>
      <%= form.text_field :search, value: params[:search], class: "form-control" %>
    </div>

    <div class="col-md-4">
      <%= form.label :category, "Search by category" %>
      <%= form.select :category, options_for_select(@categories.unshift(""), selected: params[:category]), {}, class: "form-select" %>
    </div>

    <div class="col-md-2 d-flex align-items-end">
      <%= form.submit "Filter", class: "btn btn-outline-primary w-100" %>
    </div>
  <% end %>

  <table class="table table-bordered table-striped">
    <thead class="table">
      <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>ACL/ABV</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.name %></td>
          <td><%= ingredient.category %></td>
          <td><%= ingredient.description %></td>
          <td><%= ingredient.alcohol_percentage %></td>
          <% if current_user.role.to_s.downcase == "manager" %>
            <% unless pin_login? %>
              <td>
                <%= link_to "Edit", edit_ingredient_path(ingredient), class: "btn btn-sm btn-outline-secondary me-2" %>
                <%= button_to "Delete", ingredient_path(ingredient), method: :delete, data: { confirm: "Delete ingredient?" }, class: "btn btn-sm btn-danger" %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% unless pin_login? %>
    <% if current_user.role.downcase == "manager" %>
      <%= link_to "Add a new ingredient", new_ingredient_path, class: "btn btn-outline-secondary mt-3" %>
    <% end %>
  <% end %>
</div>

app/views/ingredients/new.html.erb
<h1>Add a new ingredient</h1>
<div class="container mt-5">
  <% unless pin_login? %>
    <div>
      <%= form_with model: @ingredient, url: ingredients_path, local: true do |form| %>
        <div class="form-group">
          <%= form.label :name%>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group mt-3">
          <%= form.label :category%>
          <%= form.text_field :category, list: "category-options", class: "form-control" %>
          <datalist id="category-options">
             <% Ingredient.distinct.pluck(:category).compact.each do |cat| %>
                <option value="<%= cat %>">
             <% end %>
          </datalist>
        </div>

        <div class="form-group mt-3">
          <%= form.label :description%>
          <%= form.text_field :description, class: "form-control", rows: 3 %>
        </div>

        <div class="form-group mt-3">
          <%= form.label :alcohol_percentage, "ACL/VOL" %>
          <%= form.number_field :alcohol_percentage, step: 0.1, class: "form-control" %>
        </div>

        <div class="form-group mt-4">
          <%= form.submit "Add ingredient", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>