config/routes.rb
Rails.application.routes.draw do
  get "develop_cocktails/new"
  get "develop_cocktails/create"
  get "develop_cocktails/index"
  get "develop_cocktails/show"
  get "games/index"
  get "games/show"
  get "games/submit"
  get "cocktails/index"
  get "cocktails/new"
  get "cocktails/create"
  get "cocktails/show"
  get "ingredients/new"
  get "ingredients/create"
  #get "user/new"
  #get "user/create"
  #get "dashboard/index"
  #get "sessions/new"
  #get "sessions/create"
  #get "sessions/destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "sessions#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"
  get "/dashboard", to: "dashboard#index"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/users", to: "users#index"
  get "/ingredients/new", to: "ingredients#new", as: "new_ingredient"
  post "/ingredients", to: "ingredients#create"
  get "/ingredients", to: "ingredients#index"
  get "/cocktail_game", to: "games#index", as: "cocktail_game"
  get "/cocktail_game/:id", to: "games#show", as: "play_cocktail_game"
  post "/cocktail_game/:id/submit", to: "games#submit", as: "submit_cocktail_guess"
  resources :cocktails, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :ingredients, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :develop_cocktails
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Baronrails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary px-4">
    <div class="container-fluid flex-wrap">
      <%= link_to "Bar on Rails", dashboard_path, class: "navbar-brand text-light me-4 mb-2" %> <!-- go back to homepage -->

      <% if current_user.present? %> <!-- always available links -->
        <div class="d-flex flex-wrap align-items-center">
          <%= link_to "Search cocktails", cocktails_path, class: "nav-link text-light me-3" %>
          <%= link_to "Search ingredient", ingredients_path, class: "nav-link text-light me-3" %>

          <% unless pin_login? %> <!-- links password login -->
            <%= link_to "Game", cocktail_game_path, class: "nav-link text-light me-3" %>

            <% if current_user.role.downcase == "manager" || current_user.role.downcase == "supervisor" %> <!-- manager and supervisor development cocktail -->
              <%= link_to "Development", develop_cocktails_path, class: "nav-link text-light me-3" %>
            <% end %>

            <% if current_user.role.downcase == "manager" %> <!-- only for manager links -->
              <%= link_to "Create cocktail", new_cocktail_path, class: "nav-link text-light me-3" %>
              <%= link_to "Add ingredient", new_ingredient_path, class: "nav-link text-light me-3" %>
            <% end %>

            <% if current_user.role.downcase == "admin" %>
              <%= link_to "View users", users_path, class: "nav-link text-light me-3" %>
            <% end %>
          <% end %>

          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link text-light me-3" %>
        </div>
      <% end %>
    </div>
  </nav>

  <div class="main-content container mt-5 mb-5">
    <div class="container mt-3">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
    </div>
  <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"integrity="sha384-pE3EoOZ3AVrLkkR1V49aM6kLkz/kVy1qHnxsL+Zq0wZ7DhIKy5XlpmrNJoTkS9gZ" crossorigin="anonymous"></script>
  </body>
</html>